apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: amcart-backend-api-rule
  namespace: amcart-backend
spec:
  hosts:
    - amcart-backend
  gateway: kyma-system/kyma-gateway
  service:
    name: amcart-backend
    namespace: amcart-backend
    port: 8080
  rules:
    - path: /*
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      noAuth: true
